#!/bin/bash

jupyter labextension install @jupyterlab/fasta-extension @jupyterlab/geojson-extension @jupyterlab/katex-extension @jupyterlab/plotly-extension @jupyterlab/vega2-extension @jupyterlab/vega3-extension
#jupyter labextension install --symlink --py --sys-prefix jupyterlab_plotly
#jupyter labextension enable --py --sys-prefix jupyterlab_plotly